Feature/landing page/footer styling
Lambda-School-Labs/Express_Groomer-TeamA-FE pull request #34
Opened 2021-01-14 01:13 UTC by cdlafortune

## Description
This pull request moves the footer down to the bottom of the page and fixes the issue where the footer was not at the bottom of the page when the content was not 100% of the screen height. 
Type
- [X] This is a bugfix.
- [ ] This is a new feature.
- [X] This is part of a feature.
## Organization
- [ ] Have you linked this pull request to a Trello card?
- [X] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing
## Review
- [ ] Is this a work in progress?
- [X]  Is this ready to be reviewed?
- [X]  Have you added two reviewers to this pull request?

2021-01-15 00:32 UTC, CodyBrewer requested changes
It definitely looks better than the orange. I ran the changes in [WAVE](https://wave.webaim.org/extension/) and it looks like it's still not enough of a contrast between the text and the background. For better accessibility, it looks like the recommendations are to darken the background color or the text. 
I've uploaded some images to help explain the contrast issue. 
[Original](https://i.imgur.com/nbuRRif.png)
[Darken Text](https://i.imgur.com/5CDCKsM.png)
[Darken Background](https://imgur.com/WQ0vz0O.png)

Let me know if you have questions on this!

2021-01-15 02:08 UTC, CodyBrewer approved these changes
Looks great! thanks for adjusting th contrast

2021-01-16 05:57 UTC, jarrod847 approved these changes

2021-01-16 05:57 UTC, jarrod847 approved these changes

2021-01-16 05:57 UTC, merged